### PR TITLE
Rewrite in Typescript or in modern Javascript

### PR DESCRIPTION
**Pull request by julien-c**
Thanks for sharing this script, it's been very helpful.

Here I submit a rewrite to Typescript that I'm using on my side.

If there's interest from the maintainers (@tristen @xPaw @tripu @harimohanraj89) and the community, I'm happy to spend a little more time to try to get this merged and address any questions you might have.

Thanks for reading!

### CODE REVIEW

**Comment by tripu** [comment]
Hi, @julien-c.

A few questions, if I may:

* Don't you need to update at least `package.json` and the Gruntfile too, to add dependencies (like a transpiler) and change how the build is made and the tests run?
* What would you say are the benefits of this change?
* May we keep the current code style (eg, 2-space indentation)?

Thank you for contributing!

**Comment by julien-c** [comment]
- Yes the tooling is not in place, wanted to see if there was an interest first.
- Potential benefits:
    - Modern javascript: a few syntactic advantages, for instance you spend less time hand-coding loops, and use find/filter/map more. Code is slightly more compact.
    - Typescript: here the compiler helps you a lot because it knows about the type of the variables you're interacting with (for instance from the DOM). This both simplifies maintenance and decreases the risk for bugs.
- Of course!

**Comment by tripu** [comment]
* OK.
* I particularly don't have much interest in switching to TS, but I do want to migrate to more modern JS. Note that in order to do so while keeping [current browser support](https://github.com/tristen/tablesort/blob/gh-pages/README.md#browser-support) we do have to transpile: for instance, [IE does not support `array.prototype.find`](https://caniuse.com/#feat=array-find).
* :+1:

I'd say interest in changes (in general) is proportional to completeness of the specific changes suggested, and willingness to keep contributing and to maintain them! :slightly_smiling_face:

**Comment by julien-c** [comment]
Thanks for your response @tripu. Seems like this would need a little bit more involvement/bandwidth than I can currently spare. 

Maybe we can just close this and paste to a gist/another repo for potentially interested users.

In the meantime, feel free to close.

**Comment by tripu** [comment]
Closing since it's incomplete

**Pull request closed without merging**
