### PR TITLE
fix #62 - sort-default direction is backwards

### LINKED ISSUE #62: sort-default direction is backwards
Specifying the defaut sort dir (via the "descending" option on object instantiation) and giving a `<th>` the "sort-default" class results in the opposite sort direction.

[http://jsfiddle.net/4auneqkk/1/](http://jsfiddle.net/4auneqkk/1/)

### PR DESCRIPTION
**Pull request by timbowhite**

### CODE REVIEW

**Comment by tristen** [comment]
Hey @timbowhite sweet!

Can you pull the `customSort` commit out of this pull request and submit separately? Also it looks like Travis tests are failing here. You can run them locally via `npm test`.

**Comment by ryanmjacobs** [comment]
I agree with @tristen, you should checkout 0d47bdd into a new branch and submit a PR for that.

Also, I've realized that the "dot separated numbers" test is wrong. I've submitted PR #65 for that. Maybe we should correct the tests first?

**Comment by ryanmjacobs** [comment]
Okay, I cherry-picked 6054a73 into my own branch and updated the tests to accommodate ascending order. You can view the branch here: https://github.com/ryanmjacobs/tablesort/tree/default-sort-direction.

All tests are passing, btw. Here's the demo page: http://ryanmjacobs.github.io/tablesort/demo/.

**Comment by xPaw** [comment]
@ryanmjacobs Can confirm, that commit does fix the issue.

**Comment by xPaw** [comment]
It also looks like that commit remove the need for `update` param in `sortTable` function, would be good to get rid of that too.

**Comment by ryanmjacobs** [comment]
@xPaw Okay, I've removed the `update` param from `sortTable` and merged the fix.
@timbowhite You should re-title this as "Add customsort" or something like that because #62 should be fixed now.

**Comment by xPaw** [comment]
This issue was fixed, so I will close this PR.

**Pull request closed without merging**
