### PR TITLE
We should look at more than the first element to decide on sort function

### PR DESCRIPTION
**Pull request by matstc**
It's possible that the first row contain numbers but that the rows should still be sorted alphabetically. This PR looks at the first two and the last two rows before deciding on the sort function. Only if all 4 values agree will it choose the `sortNumber` or the `sortDate` function.

### CODE REVIEW

**Comment by tristen** [comment]
@matstc I should have responded to this eons ago. My gut reaction (when submitted and now) is that this adds a bunch of complexity before a sorting algorithm has been initialized to a corner case. It would be good to see a failing test example & [fsperf](http://jsperf.com/) comparison to ensure perfomance doesn't drop in a big way.

**Comment by matstc** [comment]
@tristen I understand it adds some complexity, but the performance cost should be constant: it will just check two more items before settling on a sort function. That extra bit of robustness was useful in my case.

**Comment by tristen** [comment]
@matstc gotcha. I think that bit of robustness would be useful too. Would welcome an updated pull request for this!

**Comment by matstc** [comment]
@tristen I just updated the PR. Let me know what you think.

**Comment by tristen** [comment]
@matstc Sorry again for delaying here. Can you rebase your branch instead? I'd like to retain a linear commit history as much as possible.

**Comment by matstc** [comment]
All right. Here's a simpler PR.

**Comment by tristen** [comment]
@matstc :+1:

**Pull request merged**
