### PR TITLE
add another sort type: "dot separated numbers"

### PR DESCRIPTION
**Pull request by ryanmjacobs**
First of all, thanks for this fantastic project.

My project needed to support sorted IP addresses, so I implemented it myself.

The sorting method is solid as far as I can tell; you can run [this test](https://gist.github.com/ryanmjacobs/b3eab5da2780c106a2a2) for yourself if you want. As a side affect, this also brings support for version numbers just like [Sortable] (http://github.hubspot.com/sortable/docs/welcome/) does.

## demo
* [before](http://jsfiddle.net/z1j96a2k/1/)
* [after](http://jsfiddle.net/2hrka0k6/2/)

### CODE REVIEW

**Comment by tristen** [comment]
@ryanmjacobs this is great! A couple things:

- Can you [add to the list here](https://github.com/tristen/tablesort#sort-types) of this additional sort type?
- It would be ideal to have a [test written here](https://github.com/tristen/tablesort/blob/gh-pages/test/index.html) for this addition. I haven't tested this out fully and I'd hate to break existing numerical patterns like currency, negative intergers, etc.

**Comment by ryanmjacobs** [comment]
Hey @tristen, I've updated the README and fixed those extra spaces. I'll write those tests later tonight.

**Comment by ryanmjacobs** [comment]
I ran `npm install` and got the build system up and running, but I don't understand how to write the tests. I added an extra column and don't know where to go from there.

**Comment by tristen** [comment]
@ryanmjacobs When you run `npm test` do the current tests pass? A new test should be written as a called [tape](https://github.com/substack/tape/) function like here: https://github.com/tristen/tablesort/blob/gh-pages/test/index.html#L53-L65.

**Comment by ryanmjacobs** [comment]
The current test run fine. I know the version sorting works fine, too.

out

But I *cannot* get these tests to work. I've tried:
``` js
// Test the sixth column has sorted
t.equal(table.rows[1].cells[5].innerHTML, "11.0.1", "sorted");
t.equal(table.rows[2].cells[5].innerHTML, "18.0.1284.49", "sorted");
t.equal(table.rows[3].cells[5].innerHTML, "31.0.1650.57", "sorted");
```

I don't think I'm using tape correctly, can you please help me? Thanks.

**Pull request merged**
