### PR TITLE
Add component.json

### PR DESCRIPTION
**Pull request by cobbweb**
Submit as a package once tests are written.

### CODE REVIEW

**Comment by tristen** [comment]
We're supporting bower and npm. punting on component support.

**Comment by jwerle** [comment]
Hmm.. That's very unfortunate. Looks like we'll just have to use duo
instead.

**Comment by jwerle** [comment]
Any particular reason why not ?

**Comment by tristen** [comment]
Mainly this:

> Remember you can install components via Git URLs.

But also because it's another package manager script to maintain.

**Pull request closed without merging**
