### PR TITLE
Use aria-sort instead of a class (redux)

### PR DESCRIPTION
**Pull request by tripu**
@chaals' #109, but adapting tests to the new attributes/values, passing tests, and rebuilding the minified version.

### CODE REVIEW

**Comment by tripu** [comment]
@tristen, what do you think of this proposal?

Our organisation is planning to use tablesort, but there are a11y requirements that we consider important. Could you take a look at this PR? If you don't like the changes, it's fine&nbsp;&mdash;&nbsp;just let us know so we can move on and pick a different library.

Thanks.

**Comment by jcsteh** [comment]
Note that if you don't want to get rid of the classes for some reason (e.g. breaking existing CSS), you could have aria-sort in addition to the classes. While redundant, it means we get accessibility without breaking backwards compat.

**Comment by tristen** [comment]
@tripu @jcsteh @chaals apologies for dragging my heels with this. I like this proposal (and the name changes) but yeah - it's a breaking change and I really need to update the codebase for tests as they currently don't work for me. I just need to find time to do that soon.

**Comment by tripu** [comment]
> Note that if you don't want to get rid of the classes for some reason (e.g. breaking existing CSS), you could have aria-sort in addition to the classes. While redundant, it means we get accessibility without breaking backwards compat.

@jcsteh, good point. I have just restored the original classes, and I believe there should be no breaking changes now.

> I like this proposal (and the name changes) but yeah - it's a breaking change and I really need to update the codebase for tests as they currently don't work for me.

@tristen, great, then :) See above&nbsp;&mdash;&nbsp;hopefully there are no breaking changes. And [tests are passing](https://travis-ci.org/tristen/tablesort/builds/179439852), right?

**Comment by tristen** [comment]
@tripu err can you revert https://github.com/tristen/tablesort/pull/115/commits/1b94c60cb078423ec90060b7a6e92a7c5248f7e6 please? Let's not keep these old class names around. I'm fine with pushing a major release.

**Comment by tripu** [comment]
@tristen: done, ready. (Note that the README and the demo need updates too now that those classes are gone.)

**Comment by tripu** [comment]
eg, sorting arrows don't appear on the demo now, cf [`tripu.github.io/tablesort/demo`](https://tripu.github.io/tablesort/demo/).

**Comment by tripu** [comment]
Hi, @tristen. Any chance we can get this merged soon?

**Comment by tristen** [comment]
@tripu I promise it will be this year :p I'm happy to merge this now but I'd like to update some build/test stuff before publishing a new release.

**Pull request merged**
