### PR TITLE
Add support for other elements than table, add support for saving the sorted column to cookies

### PR DESCRIPTION
**Pull request by Artsu**
I had a project where for certain reasons I had to use table like structure that I created using divs and css. I needed to add support for sorting so I expanded the tablesort in a way that it now supports other html elements than just table as long as certain css classes are included.

Example:
```
<div class="table" id='div-table-sort'>
  <div class="thead">
    <div class="tr"><div class='th'>Div table</div></div>
  </div>
  <div class="tbody">
    <div class="tr"><div class="td">2</div></div>
    <div class="tr"><div class="td">1</div></div>
    <div class="tr"><div class="td">3</div></div>
  </div>
</div>
```

I also added support for saving the sorted column to cookies when tablesort is given `saveToCookie` option where the value is the name of the cookie used.

*My editor did some funky things with the indentation please ignore those..*

### CODE REVIEW

**Comment by tristen** [comment]
Hey @Artsu sorry for the delay!

I like the idea of supporting other list structures other than `<table>` but I'm not sure this is the right approach. 

- It transforms div's into a table. Does it really need to do this?
- It's dependent on class names to exist that represent HTML elements. This could be agnostic by reviewing the parent -> child structure.

Also, I'd much rather see `saveToCookie` in a separate pull request.

cc @ryanmjacobs @xPaw

**Comment by xPaw** [comment]
I don't think this is needed in this library, there's [List.js](http://www.listjs.com/) which might be a better fit for this. Also saving any client side data in cookies is absolutely awful.

**Comment by Artsu** [comment]
No problem for the delay!

It doesn't really transform divs into tables. It just gives div elements the same functions that the corresponding table elements got so that I didn't need to touch the actual logic. Also whenever I've seen divs be used as table it's because actual table couldn't be used (eg. forms for every row). And since you want the divs to act like table you have to give them proper styles and usually it is done by using the table element name as class name and then styling with css. It's not really something you should ever be doing but unfortunately it's something that has to be or already has been done and then you'd might want to have the same possibility for sorting as with normal table.

@xPaw: List.js didn't really do what I wanted which is why I had to expand this library in the first place. I don't really feel like saving client side data in cookies is "absolutely awful" but you're right that I should've used local storage instead. I just thought it wasn't supported by older IE versions but I should've actually checked that.

I don't really mind if you don't merge any of this code since I just happened to have a need for it myself and decided might as well make a pull request. So no offense taken if you decide to ditch the chances completely:) Also for the same reason I probably won't be going back to make these into separate pull requests. It was more of a dumping what I made for myself instead of expanding the library for greater good, sorry.

**Comment by tristen** [comment]
OK thanks - going to close this.

**Pull request closed without merging**
