### PR TITLE
Correctly handle sorting when colspans are present

### PR DESCRIPTION
**Pull request by decklin**
This should deal with https://github.com/tristen/tablesort/issues/48, which I ran into. In order to get the column something will appear to be visually, you need to look at the whole row (at least up to the cell in question) and add up colspans. Hopefully this is the least intrusive way to do that.

### CODE REVIEW

**Comment by decklin** [comment]
Here's a demo of the changes if you want to see it: https://decklin.github.io/botw-arrow-prices/

**Comment by tristen** [comment]
Great! 👍 can you also add a test by adding an [example here](https://github.com/tristen/tablesort/blob/gh-pages/test/index.html) that mocks a table for colspans and testing the correct output of values here https://github.com/tristen/tablesort/blob/gh-pages/test/spec/tablesort.js?

**Comment by tristen** [comment]
Hm so I made a quick example to test this patch and unless I am misunderstanding, I'm don't see it addressing the issue cited in #48 https://jsfiddle.net/tristen/byws086t/

**Comment by tristen** [comment]
Superceded by https://github.com/tristen/tablesort/pull/181

**Pull request closed without merging**
